name: build and deploy

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build:ci
      - run: cp dist/virtual-shop-unit/index.html dist/virtual-shop-unit/404.html
      - run: ls
      - run: ls dist/virtual-shop-unit
      - run: touch .nojekyll
      - uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: dist/virtual-shop-unit
          if-no-files-found: error
  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
